#include "print_ship_info.h"
#include "ship.h"

#include <string>
#include <iostream>

void print_ship_info(ship* xship){
    cout << "SHIP INFO:" << endl;
    cout << "\tId: " << xship->read_id() << endl;
    cout << "\tMesh: " << xship->read_mesh() << endl;
    cout << "\tName: " << xship->read_name() << endl;
    cout << "\tGal_x,y,z: " << xship->read_gal_x() << "," << xship->read_gal_y() << "," << xship->read_gal_z() << endl;
    cout << "\tLoc_x,y,z: " << xship->read_loc_x() << "," << xship->read_loc_y() << "," << xship->read_loc_z() << endl;
    cout << "\tSize: " << xship->read_shipsize() << endl;
    cout << "\tCargo: " << xship->read_cargo() << endl;
    cout << "\tDim_x: " << xship->read_dim_x() << endl;
    cout << "\tDim_y: " << xship->read_dim_y() << endl;
    cout << "\tDim_z: " << xship->read_dim_z() << endl;
    cout << "\tMass: " << xship->read_mass() << endl;
    cout << "\tShield Max: " << xship->read_shield_max() << endl;
    cout << "\tShield HP: " << xship->read_shield_hp() << endl;
    cout << "\tArmor Thickness: " << xship->read_armor_thickness() << endl;
    cout << "\tArmor Hardness: " << xship->read_armor_hardness() << endl;
    cout << "\tVec_pos_x: " << xship->read_vec_pos_x(0) << endl;
    cout << "\tVec_pos_y: " << xship->read_vec_pos_y(1) << endl;
    cout << "\tVec_pos_z: " << xship->read_vec_pos_z(2) << endl;
    cout << "\tVec_velo_x: " << xship->read_vec_velo_x(0) << endl;
    cout << "\tVec_velo_y: " << xship->read_vec_velo_y(1) << endl;
    cout << "\tVec_velo_z: " << xship->read_vec_velo_z(2) << endl;
    cout << "\tShield: " << xship->read_mod_shield()->read_name() << endl;
    cout << "\t\tSize: " << xship->read_mod_shield()->read_modsize() << endl;
    cout << "\t\tDamage: " << xship->read_mod_shield()->read_damage() << endl;
    cout << "\t\tField Max: " << xship->read_mod_shield()->read_field_max() << endl;
    cout << "\t\tPower Max: " << xship->read_mod_shield()->read_power_max() << endl;
    cout << "\t\tPower: " << xship->read_mod_shield()->read_power() << endl;
    cout << "\tArmor: " << xship->read_mod_armor()->read_name() << endl;
    cout << "\t\tSize: " << xship->read_mod_armor()->read_modsize() << endl;
    cout << "\t\tDamage: " << xship->read_mod_armor()->read_damage() << endl;
    cout << "\t\tHardness Max: " << xship->read_mod_armor()->read_hardness_max() << endl;
    cout << "\t\tHardness: " << xship->read_mod_armor()->read_hardness() << endl;
    cout << "\t\tThickness Max: " << xship->read_mod_armor()->read_thickness_max() << endl;
    cout << "\t\tThickness: " << xship->read_mod_armor()->read_thickness() << endl;
    cout << "\tReactor: " << xship->read_mod_reactor()->read_name() << endl;
    cout << "\t\tSize: " << xship->read_mod_reactor()->read_modsize() << endl;
    cout << "\t\tDamage: " << xship->read_mod_reactor()->read_damage() << endl;
    cout << "\t\tPower Max: " << xship->read_mod_reactor()->read_power_max() << endl;
    cout << "\t\tPower: " << xship->read_mod_reactor()->read_power() << endl;
    cout << "\tCapacitor: " << xship->read_mod_capacitor()->read_name() << endl;
    cout << "\t\tSize: " << xship->read_mod_capacitor()->read_modsize() << endl;
    cout << "\t\tDamage: " << xship->read_mod_capacitor()->read_damage() << endl;
    cout << "\t\tCapacitance Max: " << xship->read_mod_capacitor()->read_capacitance_max() << endl;
    cout << "\t\tPower Max: " << xship->read_mod_capacitor()->read_power_max() << endl;
    cout << "\t\tPower: " << xship->read_mod_capacitor()->read_power() << endl;
    cout << "\tHyperdrive: " << xship->read_mod_hyperdrive()->read_name() << endl;
    cout << "\t\tSize: " << xship->read_mod_hyperdrive()->read_modsize() << endl;
    cout << "\t\tDamage: " << xship->read_mod_hyperdrive()->read_damage() << endl;
    cout << "\t\tIntra Power Max: " << xship->read_mod_hyperdrive()->read_intra_power_max() << endl;
    cout << "\t\tIntra Power: " << xship->read_mod_hyperdrive()->read_intra_power() << endl;
    cout << "\t\tIntra Speed Max: " << xship->read_mod_hyperdrive()->read_intra_speed_max() << endl;
    cout << "\t\tIntra Speed: " << xship->read_mod_hyperdrive()->read_intra_speed() << endl;
    cout << "\t\tInter Power Max: " << xship->read_mod_hyperdrive()->read_inter_power_max() << endl;
    cout << "\t\tInter Power: " << xship->read_mod_hyperdrive()->read_inter_power() << endl;
    cout << "\t\tInter Speed Max: " << xship->read_mod_hyperdrive()->read_inter_speed_max() << endl;
    cout << "\t\tInter Speed: " << xship->read_mod_hyperdrive()->read_inter_speed() << endl;
    cout << "\tInertial: " << xship->read_mod_inertial()->read_name() << endl;
    cout << "\t\tSize: " << xship->read_mod_inertial()->read_modsize() << endl;
    cout << "\t\tDamage: " << xship->read_mod_inertial()->read_damage() << endl;
    cout << "\t\tSpeed Max: " << xship->read_mod_inertial()->read_speed_max() << endl;
    cout << "\t\tSpeed: " << xship->read_mod_inertial()->read_speed() << endl;
    cout << "\t\tRotspeed Max: " << xship->read_mod_inertial()->read_rotspeed_max() << endl;
    cout << "\t\tRotspeed: " << xship->read_mod_inertial()->read_rotspeed() << endl;
    cout << "\tLRSensor: " << xship->read_mod_lrsensor()->read_name() << endl;
    cout << "\t\tSize: " << xship->read_mod_lrsensor()->read_modtype() << endl;
    cout << "\t\tDamage: " << xship->read_mod_lrsensor()->read_damage() << endl;
    cout << "\t\tRange Max: " << xship->read_mod_lrsensor()->read_range_max() << endl;
    cout << "\t\tRange: " << xship->read_mod_lrsensor()->read_range() << endl;
    cout << "\t\tTime Max: " << xship->read_mod_lrsensor()->read_time_max() << endl;
    cout << "\t\tTime: " << xship->read_mod_lrsensor()->read_time() << endl;
    cout << "\t\tAccuracy Max: " << xship->read_mod_lrsensor()->read_accuracy_max() << endl;
    cout << "\t\tAccuracy: " << xship->read_mod_lrsensor()->read_accuracy() << endl;
    cout << "\tSRSensor: " << xship->read_mod_srsensor()->read_name() << endl;
    cout << "\t\tSize: " << xship->read_mod_srsensor()->read_modtype() << endl;
    cout << "\t\tDamage: " << xship->read_mod_srsensor()->read_damage() << endl;
    cout << "\t\tRange Max: " << xship->read_mod_srsensor()->read_range_max() << endl;
    cout << "\t\tRange: " << xship->read_mod_srsensor()->read_range() << endl;
    cout << "\t\tTime Max: " << xship->read_mod_srsensor()->read_time_max() << endl;
    cout << "\t\tTime: " << xship->read_mod_srsensor()->read_time() << endl;
    cout << "\t\tAccuracy Max: " << xship->read_mod_srsensor()->read_accuracy_max() << endl;
    cout << "\t\tAccuracy: " << xship->read_mod_srsensor()->read_accuracy() << endl;
    cout << "\t\tTarget Max: " << xship->read_mod_srsensor()->read_target_max() << endl;
    cout << "\t\tTarget: " << xship->read_mod_srsensor()->read_target() << endl;
    cout << "\t\tTarget Locked: " << xship->read_mod_srsensor()->read_target_locked() << endl;
    cout << "\tThruster 0: " << xship->read_mod_thruster(0)->read_name() << endl;
    cout << "\t\tSize: " << xship->read_mod_thruster(0)->read_modsize() << endl;
    cout << "\t\tDamage: " << xship->read_mod_thruster(0)->read_damage() << endl;
    cout << "\t\tThrust Max: " << xship->read_mod_thruster(0)->read_thrust_max() << endl;
    cout << "\t\tThrust: " << xship->read_mod_thruster(0)->read_thrust() << endl;
    cout << "\t\tPower Max: " << xship->read_mod_thruster(0)->read_power_max() << endl;
    cout << "\t\tPower: " << xship->read_mod_thruster(0)->read_power() << endl;
    cout << "\tThruster 1: " << xship->read_mod_thruster(1)->read_name() << endl;
    cout << "\t\tSize: " << xship->read_mod_thruster(1)->read_modsize() << endl;
    cout << "\t\tDamage: " << xship->read_mod_thruster(1)->read_damage() << endl;
    cout << "\t\tThrust Max: " << xship->read_mod_thruster(1)->read_thrust_max() << endl;
    cout << "\t\tThrust: " << xship->read_mod_thruster(1)->read_thrust() << endl;
    cout << "\t\tPower Max: " << xship->read_mod_thruster(1)->read_power_max() << endl;
    cout << "\t\tPower: " << xship->read_mod_thruster(1)->read_power() << endl;
    cout << "\tThruster 2: " << xship->read_mod_thruster(2)->read_name() << endl;
    cout << "\t\tSize: " << xship->read_mod_thruster(2)->read_modsize() << endl;
    cout << "\t\tDamage: " << xship->read_mod_thruster(2)->read_damage() << endl;
    cout << "\t\tThrust Max: " << xship->read_mod_thruster(2)->read_thrust_max() << endl;
    cout << "\t\tThrust: " << xship->read_mod_thruster(2)->read_thrust() << endl;
    cout << "\t\tPower Max: " << xship->read_mod_thruster(2)->read_power_max() << endl;
    cout << "\t\tPower: " << xship->read_mod_thruster(2)->read_power() << endl;
    cout << "\tThruster 3: " << xship->read_mod_thruster(3)->read_name() << endl;
    cout << "\t\tSize: " << xship->read_mod_thruster(3)->read_modsize() << endl;
    cout << "\t\tDamage: " << xship->read_mod_thruster(3)->read_damage() << endl;
    cout << "\t\tThrust Max: " << xship->read_mod_thruster(3)->read_thrust_max() << endl;
    cout << "\t\tThrust: " << xship->read_mod_thruster(3)->read_thrust() << endl;
    cout << "\t\tPower Max: " << xship->read_mod_thruster(3)->read_power_max() << endl;
    cout << "\t\tPower: " << xship->read_mod_thruster(3)->read_power() << endl;
    cout << "\tThruster 4: " << xship->read_mod_thruster(4)->read_name() << endl;
    cout << "\t\tSize: " << xship->read_mod_thruster(4)->read_modsize() << endl;
    cout << "\t\tDamage: " << xship->read_mod_thruster(4)->read_damage() << endl;
    cout << "\t\tThrust Max: " << xship->read_mod_thruster(4)->read_thrust_max() << endl;
    cout << "\t\tThrust: " << xship->read_mod_thruster(4)->read_thrust() << endl;
    cout << "\t\tPower Max: " << xship->read_mod_thruster(4)->read_power_max() << endl;
    cout << "\t\tPower: " << xship->read_mod_thruster(4)->read_power() << endl;
    cout << "\tThruster 5: " << xship->read_mod_thruster(5)->read_name() << endl;
    cout << "\t\tSize: " << xship->read_mod_thruster(5)->read_modsize() << endl;
    cout << "\t\tDamage: " << xship->read_mod_thruster(5)->read_damage() << endl;
    cout << "\t\tThrust Max: " << xship->read_mod_thruster(5)->read_thrust_max() << endl;
    cout << "\t\tThrust: " << xship->read_mod_thruster(5)->read_thrust() << endl;
    cout << "\t\tPower Max: " << xship->read_mod_thruster(5)->read_power_max() << endl;
    cout << "\t\tPower: " << xship->read_mod_thruster(5)->read_power() << endl;
    cout << "\tThruster 6: " << xship->read_mod_thruster(6)->read_name() << endl;
    cout << "\t\tSize: " << xship->read_mod_thruster(6)->read_modsize() << endl;
    cout << "\t\tDamage: " << xship->read_mod_thruster(6)->read_damage() << endl;
    cout << "\t\tThrust Max: " << xship->read_mod_thruster(6)->read_thrust_max() << endl;
    cout << "\t\tThrust: " << xship->read_mod_thruster(6)->read_thrust() << endl;
    cout << "\t\tPower Max: " << xship->read_mod_thruster(6)->read_power_max() << endl;
    cout << "\t\tPower: " << xship->read_mod_thruster(6)->read_power() << endl;
    cout << "\tThruster 7: " << xship->read_mod_thruster(7)->read_name() << endl;
    cout << "\t\tSize: " << xship->read_mod_thruster(7)->read_modsize() << endl;
    cout << "\t\tDamage: " << xship->read_mod_thruster(7)->read_damage() << endl;
    cout << "\t\tThrust Max: " << xship->read_mod_thruster(7)->read_thrust_max() << endl;
    cout << "\t\tThrust: " << xship->read_mod_thruster(7)->read_thrust() << endl;
    cout << "\t\tPower Max: " << xship->read_mod_thruster(7)->read_power_max() << endl;
    cout << "\t\tPower: " << xship->read_mod_thruster(7)->read_power() << endl;
    cout << "\tHardpoint 0:" << xship->read_mod_hardpoint(0)->read_name() << endl;
    cout << "\t\tSize: " << xship->read_mod_hardpoint(0)->read_modsize() << endl;
    cout << "\t\tDamage: " << xship->read_mod_hardpoint(0)->read_damage() << endl;
    cout << "\t\tType: " << xship->read_mod_hardpoint(0)->read_type() << endl;
    cout << "\t\tAmmorack Max: " << xship->read_mod_hardpoint(0)->read_ammorack_max() << endl;
    cout << "\t\tAmmorack: " << xship->read_mod_hardpoint(0)->read_ammorack() << endl;
    cout << "\t\tPower Max: " << xship->read_mod_hardpoint(0)->read_power_max() << endl;
    cout << "\t\tPower: " << xship->read_mod_hardpoint(0)->read_power() << endl;
    cout << "\t\tForce Max: " << xship->read_mod_hardpoint(0)->read_force_max() << endl;
    cout << "\t\tForce: " << xship->read_mod_hardpoint(0)->read_force() << endl;
    cout << "\t\tAccuracy Max: " << xship->read_mod_hardpoint(0)->read_accuracy_max() << endl;
    cout << "\t\tAccuracy: " << xship->read_mod_hardpoint(0)->read_accuracy() << endl;
    cout << "\tHardpoint 1:" << xship->read_mod_hardpoint(1)->read_name() << endl;
    cout << "\t\tSize: " << xship->read_mod_hardpoint(1)->read_modsize() << endl;
    cout << "\t\tDamage: " << xship->read_mod_hardpoint(1)->read_damage() << endl;
    cout << "\t\tType: " << xship->read_mod_hardpoint(1)->read_type() << endl;
    cout << "\t\tAmmorack Max: " << xship->read_mod_hardpoint(1)->read_ammorack_max() << endl;
    cout << "\t\tAmmorack: " << xship->read_mod_hardpoint(1)->read_ammorack() << endl;
    cout << "\t\tPower Max: " << xship->read_mod_hardpoint(1)->read_power_max() << endl;
    cout << "\t\tPower: " << xship->read_mod_hardpoint(1)->read_power() << endl;
    cout << "\t\tForce Max: " << xship->read_mod_hardpoint(1)->read_force_max() << endl;
    cout << "\t\tForce: " << xship->read_mod_hardpoint(1)->read_force() << endl;
    cout << "\t\tAccuracy Max: " << xship->read_mod_hardpoint(1)->read_accuracy_max() << endl;
    cout << "\t\tAccuracy: " << xship->read_mod_hardpoint(1)->read_accuracy() << endl;
    cout << "\tHardpoint 2:" << xship->read_mod_hardpoint(2)->read_name() << endl;
    cout << "\t\tSize: " << xship->read_mod_hardpoint(2)->read_modsize() << endl;
    cout << "\t\tDamage: " << xship->read_mod_hardpoint(2)->read_damage() << endl;
    cout << "\t\tType: " << xship->read_mod_hardpoint(2)->read_type() << endl;
    cout << "\t\tAmmorack Max: " << xship->read_mod_hardpoint(2)->read_ammorack_max() << endl;
    cout << "\t\tAmmorack: " << xship->read_mod_hardpoint(2)->read_ammorack() << endl;
    cout << "\t\tPower Max: " << xship->read_mod_hardpoint(2)->read_power_max() << endl;
    cout << "\t\tPower: " << xship->read_mod_hardpoint(2)->read_power() << endl;
    cout << "\t\tForce Max: " << xship->read_mod_hardpoint(2)->read_force_max() << endl;
    cout << "\t\tForce: " << xship->read_mod_hardpoint(2)->read_force() << endl;
    cout << "\t\tAccuracy Max: " << xship->read_mod_hardpoint(2)->read_accuracy_max() << endl;
    cout << "\t\tAccuracy: " << xship->read_mod_hardpoint(2)->read_accuracy() << endl;
    cout << "\tHardpoint 3:" << xship->read_mod_hardpoint(3)->read_name() << endl;
    cout << "\t\tSize: " << xship->read_mod_hardpoint(3)->read_modsize() << endl;
    cout << "\t\tDamage: " << xship->read_mod_hardpoint(3)->read_damage() << endl;
    cout << "\t\tType: " << xship->read_mod_hardpoint(3)->read_type() << endl;
    cout << "\t\tAmmorack Max: " << xship->read_mod_hardpoint(3)->read_ammorack_max() << endl;
    cout << "\t\tAmmorack: " << xship->read_mod_hardpoint(3)->read_ammorack() << endl;
    cout << "\t\tPower Max: " << xship->read_mod_hardpoint(3)->read_power_max() << endl;
    cout << "\t\tPower: " << xship->read_mod_hardpoint(3)->read_power() << endl;
    cout << "\t\tForce Max: " << xship->read_mod_hardpoint(3)->read_force_max() << endl;
    cout << "\t\tForce: " << xship->read_mod_hardpoint(3)->read_force() << endl;
    cout << "\t\tAccuracy Max: " << xship->read_mod_hardpoint(3)->read_accuracy_max() << endl;
    cout << "\t\tAccuracy: " << xship->read_mod_hardpoint(3)->read_accuracy() << endl;
    cout << "\tHardpoint 4:" << xship->read_mod_hardpoint(4)->read_name() << endl;
    cout << "\t\tSize: " << xship->read_mod_hardpoint(4)->read_modsize() << endl;
    cout << "\t\tDamage: " << xship->read_mod_hardpoint(4)->read_damage() << endl;
    cout << "\t\tType: " << xship->read_mod_hardpoint(4)->read_type() << endl;
    cout << "\t\tAmmorack Max: " << xship->read_mod_hardpoint(4)->read_ammorack_max() << endl;
    cout << "\t\tAmmorack: " << xship->read_mod_hardpoint(4)->read_ammorack() << endl;
    cout << "\t\tPower Max: " << xship->read_mod_hardpoint(4)->read_power_max() << endl;
    cout << "\t\tPower: " << xship->read_mod_hardpoint(4)->read_power() << endl;
    cout << "\t\tForce Max: " << xship->read_mod_hardpoint(4)->read_force_max() << endl;
    cout << "\t\tForce: " << xship->read_mod_hardpoint(4)->read_force() << endl;
    cout << "\t\tAccuracy Max: " << xship->read_mod_hardpoint(4)->read_accuracy_max() << endl;
    cout << "\t\tAccuracy: " << xship->read_mod_hardpoint(4)->read_accuracy() << endl;
    cout << "\tHardpoint 5:" << xship->read_mod_hardpoint(5)->read_name() << endl;
    cout << "\t\tSize: " << xship->read_mod_hardpoint(5)->read_modsize() << endl;
    cout << "\t\tDamage: " << xship->read_mod_hardpoint(5)->read_damage() << endl;
    cout << "\t\tType: " << xship->read_mod_hardpoint(5)->read_type() << endl;
    cout << "\t\tAmmorack Max: " << xship->read_mod_hardpoint(5)->read_ammorack_max() << endl;
    cout << "\t\tAmmorack: " << xship->read_mod_hardpoint(5)->read_ammorack() << endl;
    cout << "\t\tPower Max: " << xship->read_mod_hardpoint(5)->read_power_max() << endl;
    cout << "\t\tPower: " << xship->read_mod_hardpoint(5)->read_power() << endl;
    cout << "\t\tForce Max: " << xship->read_mod_hardpoint(5)->read_force_max() << endl;
    cout << "\t\tForce: " << xship->read_mod_hardpoint(5)->read_force() << endl;
    cout << "\t\tAccuracy Max: " << xship->read_mod_hardpoint(5)->read_accuracy_max() << endl;
    cout << "\t\tAccuracy: " << xship->read_mod_hardpoint(5)->read_accuracy() << endl;
    cout << "\tHardpoint 6:" << xship->read_mod_hardpoint(6)->read_name() << endl;
    cout << "\t\tSize: " << xship->read_mod_hardpoint(6)->read_modsize() << endl;
    cout << "\t\tDamage: " << xship->read_mod_hardpoint(6)->read_damage() << endl;
    cout << "\t\tType: " << xship->read_mod_hardpoint(6)->read_type() << endl;
    cout << "\t\tAmmorack Max: " << xship->read_mod_hardpoint(6)->read_ammorack_max() << endl;
    cout << "\t\tAmmorack: " << xship->read_mod_hardpoint(6)->read_ammorack() << endl;
    cout << "\t\tPower Max: " << xship->read_mod_hardpoint(6)->read_power_max() << endl;
    cout << "\t\tPower: " << xship->read_mod_hardpoint(6)->read_power() << endl;
    cout << "\t\tForce Max: " << xship->read_mod_hardpoint(6)->read_force_max() << endl;
    cout << "\t\tForce: " << xship->read_mod_hardpoint(6)->read_force() << endl;
    cout << "\t\tAccuracy Max: " << xship->read_mod_hardpoint(6)->read_accuracy_max() << endl;
    cout << "\t\tAccuracy: " << xship->read_mod_hardpoint(6)->read_accuracy() << endl;
    cout << "\tHardpoint 7:" << xship->read_mod_hardpoint(7)->read_name() << endl;
    cout << "\t\tSize: " << xship->read_mod_hardpoint(7)->read_modsize() << endl;
    cout << "\t\tDamage: " << xship->read_mod_hardpoint(7)->read_damage() << endl;
    cout << "\t\tType: " << xship->read_mod_hardpoint(7)->read_type() << endl;
    cout << "\t\tAmmorack Max: " << xship->read_mod_hardpoint(7)->read_ammorack_max() << endl;
    cout << "\t\tAmmorack: " << xship->read_mod_hardpoint(7)->read_ammorack() << endl;
    cout << "\t\tPower Max: " << xship->read_mod_hardpoint(7)->read_power_max() << endl;
    cout << "\t\tPower: " << xship->read_mod_hardpoint(7)->read_power() << endl;
    cout << "\t\tForce Max: " << xship->read_mod_hardpoint(7)->read_force_max() << endl;
    cout << "\t\tForce: " << xship->read_mod_hardpoint(7)->read_force() << endl;
    cout << "\t\tAccuracy Max: " << xship->read_mod_hardpoint(7)->read_accuracy_max() << endl;
    cout << "\t\tAccuracy: " << xship->read_mod_hardpoint(7)->read_accuracy() << endl;
    return;
}
